{% set version = "0.5.2" %}
{% set sha256 = "f8ced9b02293a6699433b88c0606ad92d7f4fc168d3d87ac3f87cfbca700266d" %}
{% set name = "elf" %}

package:
  name: python-elf
  version: {{ version }}

source:
  url: https://github.com/constantinpape/elf/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - affogato
    - imageio
    - h5py
    - mrcfile
    - nifty >=1.1
    - numba
    - numpy <2
    - pandas
    - scikit-image
    - scikit-learn
    - skan >=0.11.1
    - threadpoolctl
    - tqdm
    - vigra
    - z5py >=2.0.10

test:
  requires:
    - requests
  imports:
    - elf
    - elf.io
    - elf.transformation
    - elf.segmentation
  source_files:
    - test/**/*.py
    - data/**
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Utils and convenience functions for large-scale bio-image analysis.
  home: https://github.com/constantinpape/elf

extra:
  recipe-maintainers:
    - constantinpape
